version: '2.3'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile.template
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HEALTHCHECK_PORT: 8000
